# Generated by Django 5.0.3 on 2024-03-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='estado_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.estado_produto'),
        ),
    ]
