# Generated by Django 5.0.3 on 2024-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_estado_produto_produtos_estado_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=1500),
        ),
    ]
