# Generated by Django 5.0.3 on 2024-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_alter_produtos_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('CPF_CNPJ', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Senha', models.CharField(max_length=250)),
                ('Telefone', models.CharField(max_length=250)),
                ('Tipo', models.CharField(max_length=250)),
                ('Endereço', models.CharField(max_length=250)),
            ],
        ),
    ]
