# Generated by Django 5.0.3 on 2024-04-12 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_tipo_usuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.categoria_produto'),
        ),
    ]
