# Generated by Django 5.0.3 on 2024-04-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_pagamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Endereço',
            new_name='Endereco',
        ),
    ]
