# Generated by Django 5.0.3 on 2024-04-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0012_estado_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Endereco',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mercado.cep'),
        ),
    ]
