# Generated by Django 5.0.3 on 2024-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0015_endereco_usuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
