# Generated by Django 5.0.3 on 2024-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0016_usuario_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='total_preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
