# Generated by Django 5.0.3 on 2024-05-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0017_pagamento_total_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Senha',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Cep',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
